feat: loop
molend-labs/molend-protocol pull request #7
Opened 2024-03-15 02:43 UTC by neko202402

2024-03-20 04:05 UTC, asimof requested changes

2024-03-20 04:05 UTC, asimof commented on contracts/protocol/lendingpool/Looping.sol
> +    if (asset == address(WETH)) {
If attached ether > 0 and asset is WETH, we can assume it's looping ETH?

2024-03-20 04:05 UTC, asimof commented on contracts/protocol/lendingpool/Looping.sol
> +    if (asset == address(WETH)) {
If user just want to loop WETH, I think we should still allow that.

2024-03-20 04:05 UTC, asimof commented on contracts/protocol/lendingpool/Looping.sol
> +    LENDING_POOL.borrow(asset, borrowed, 2, 0, user); // TODO interestRateMode
In practice, only allow variable rate mode is OK as we have disabled stable mode.

2024-03-20 04:09 UTC, neko202402 commented on contracts/protocol/lendingpool/Looping.sol
> +    if (asset == address(WETH)) {
1. address is 0x0, attach Ether, assume looping Ether
2. address is WETH, attach nothing, asume lopping WETH
Do you think that is OK?

2024-03-20 07:00 UTC, asimof requested changes

2024-03-20 07:00 UTC, asimof commented on contracts/protocol/lendingpool/Looping.sol
> +    if (asset == address(0)) {
why not require address is WETH when attached ether is greater than 0? It would be a bit confusing when passing a zero address.

Or we may just add another explicit function `loopETH`, so it's easier to understand by caller.

2024-03-20 07:00 UTC, asimof commented on contracts/protocol/lendingpool/Looping.sol
> +  IWETH internal immutable WETH;
Similar to WETHGateway, we may need to expose the WETH address externally so caller know which WETH is being used.

https://github.com/molend-labs/molend-protocol/blob/733fc6936f990b8f8f06f567f6bda2a1528b942b/contracts/misc/WETHGateway.sol#L169-L174

2024-03-20 09:07 UTC, molendtoby commented on contracts/protocol/lendingpool/Looping.sol
> +    address initiator,
verify that `initiator` is this contract otherwise other contract can initiate flashload again this

2024-03-26 03:15 UTC, asimof requested changes

2024-03-26 03:15 UTC, asimof commented on contracts/protocol/lendingpool/Looping.sol
> +    uint256 borrowCount
`loopCount` is more accurate I think.

2024-03-26 03:23 UTC, asimof commented on contracts/protocol/lendingpool/Looping.sol
> +contract Looping {
We can move the contract to `misc` folder. Similar to `WETHGateway`, `Looping` extends the functionalities of core lending pool contracts.

2024-03-27 04:53 UTC, asimof requested changes

2024-03-27 04:53 UTC, asimof commented on contracts/misc/Looping.sol
> +import {IWETH} from "../misc/interfaces/IWETH.sol";
```suggestion
import {IWETH} from "./interfaces/IWETH.sol";
```

2024-03-27 10:05 UTC, molendtoby commented on contracts/misc/Looping.sol
> +    LENDING_POOL.deposit(asset, amount, user, 0);
we can add an event for looping

2024-03-27 10:09 UTC, molendtoby commented on tasks/deployments/deploy-Looping.ts
> +    const looping = await new LoopingFactory(await getFirstSigner()).deploy(provider, weth);
why not using `deployLooping`?

2024-03-28 08:51 UTC, molendtoby approved these changes

2024-03-28 08:55 UTC, asimof approved these changes

2024-03-28 08:55 UTC, merged